version: '3.7'

services:
  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
      - ./entrypoint:/docker-entrypoint-initdb.d
      - ./mysqlconf:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: assignment
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: qwerty
    ports:
      - 3306:3306
    command: mysqld
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
